name: Code Coverage
on:
  push:
  pull_request:

jobs:
  codcov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}


      - name: Check code coverage
        uses: codecov/codecov-action@v2
